[workspace]
description = "Banjo is a Mojo library for terminal I/O, providing bindings to the termios library."
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["https://repo.prefix.dev/mojo-community", "conda-forge", "https://conda.modular.com/max", "https://prefix.dev/pixi-build-backends"]
platforms = ["linux-64", "osx-arm64", "linux-aarch64"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/thatstoasty/banjo"
repository = "https://github.com/thatstoasty/banjo"
preview = ["pixi-build"]

[feature.util.tasks]
tests = "sh -c 'find test -name \"test_*.mojo\" -exec mojo -D ASSERT=all -I . {} \\;'"
examples = "sh -c 'find examples -name \"*.mojo\" -exec mojo -D ASSERT=all -I . {} \\;'"

# Linting and Formatting
lint_docs = "mojo doc --Werror --diagnose-missing-doc-strings -o /dev/null ./banjo"
mojo_format = "mojo format banjo --line-length 120"
sort_imports = "isort **/*.mojo -m 3 --line-length 120 --lines-after-imports 2 --trailing-comma"
format = [{ task = "mojo_format" }, { task = "sort_imports" }]

# Build and publish
build = { cmd = "pixi build -o ." }
publish = { cmd = "find . -name 'banjo-*.conda' | xargs pixi upload https://prefix.dev/api/v1/upload/mojo-community" }
build_and_publish = [{ task = "build" }, { task = "publish" }]

[package]
name = "banjo"
version = "26.1.0"

[package.build]
backend = { name = "pixi-build-mojo", version = "*" }

[dependencies]
mojo = ">=0.26.1.0,<0.26.2.0"
mog = ">=26.1.0,<26.2.0"

[package.build-dependencies]
mojo-compiler = ">=0.26.1.0,<0.26.2.0"

[package.run-dependencies]
mojo = ">=0.26.1.0,<0.26.2.0"
# mog = ">=26.1.0,<26.2.0"

[feature.util.dependencies]
isort = ">=6.0.1,<7"

[environments]
default = { solve-group = "default" }
util = { features = ["util"], solve-group = "default" }
